version: '3'

services:

  server1:
    # image: python:latest
    build: ./app
    container_name: server1
    command: ./scripts/script.py 
    volumes:
      - "./app/scripts:/app/scripts"
    # ports:
    #   - "80:5000"

  server2:
    build: ./app2
    container_name: server2
    # command: ./scripts/script.py
    volumes:
      - "./app2/scripts:/app/scripts"
        
